export const USER_FETCH = 'app/USER_FETCH';
export const UPDATE_USER_MATCH_GROUPS = 'app/UPDATE_USER_MATCH_GROUPS';

export const USER_FETCHING = 'app/USER_FETCHING';
export const USER_FETCH_SUCCESS = 'app/USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'app/USER_FETCH_ERROR';

export const UPDATING_USER_MATCH_GROUPS = 'app/UPDATING_USER_MATCH_GROUPS';
export const UPDATE_USER_MATCH_GROUPS_SUCCESS = 'app/UPDATE_USER_MATCH_GROUPS_SUCCESS';
export const UPDATE_USER_MATCH_GROUPS_ERROR = 'app/UPDATE_USER_MATCH_GROUPS_ERROR';
